### ISSUE TITLE
Build fails under Windows with Caused by: java.net.URISyntaxException: Illegal character in path at index 19

### ISSUE THREAD

**Issue by apocarteres** [jcabi/jcabi-ssl-maven-plugin#26]
<pre>
[INFO] [WARNING] The requested profile "qulice" could not be activated because it does not exist.
[INFO] run script verify.groovy
[INFO] Running post-build script: Z:\jcabi-ssl-maven-plugin\target\it\end-to-end\verify.groovy
[INFO] Finished post-build script: Z:\jcabi-ssl-maven-plugin\target\it\end-to-end\verify.groovy
[INFO] ..SUCCESS (6.7 s)
[INFO] -------------------------------------------------
[INFO] Build Summary:
[INFO]   Passed: 1, Failed: 0, Errors: 0, Skipped: 0
[INFO] -------------------------------------------------
[INFO]
[INFO] --- qulice-maven-plugin:0.10:check (jcabi-check) @ jcabi-ssl-maven-plugin ---
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 01:36 min
[INFO] Finished at: 2015-01-27T14:38:06+03:00
[INFO] Final Memory: 39M/247M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal com.qulice:qulice-maven-plugin:0.10:check (jcabi-check) on project jcabi-ssl-maven-plugin: Execution jcabi-ch
eck of goal com.qulice:qulice-maven-plugin:0.10:check failed: Illegal character in path at index 19: file://C:/Documents and Settings/JustUs
er/.m2/repository/com/jcabi/jcabi-log/0.15.1/jcabi-log-0.15.1.jar -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal com.qulice:qulice-maven-plugin:0.10:check (jcabi-check) on pr
oject jcabi-ssl-maven-plugin: Execution jcabi-check of goal com.qulice:qulice-maven-plugin:0.10:check failed: Illegal character in path at i
ndex 19: file://C:/Documents and Settings/JustUser/.m2/repository/com/jcabi/jcabi-log/0.15.1/jcabi-log-0.15.1.jar
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:224)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:116)
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:80)
        at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
        at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:120)
        at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:355)
        at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:155)
        at org.apache.maven.cli.MavenCli.execute(MavenCli.java:584)
        at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:216)
        at org.apache.maven.cli.MavenCli.main(MavenCli.java:160)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:606)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
        at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
        at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
Caused by: org.apache.maven.plugin.PluginExecutionException: Execution jcabi-check of goal com.qulice:qulice-maven-plugin:0.10:check failed:
 Illegal character in path at index 19: file://C:/Documents and Settings/JustUser/.m2/repository/com/jcabi/jcabi-log/0.15.1/jcabi-log-0.15.1
.jar
        at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:143)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:208)
        ... 19 more
Caused by: java.lang.IllegalArgumentException: Illegal character in path at index 19: file://C:/Documents and Settings/JustUser/.m2/reposito
ry/com/jcabi/jcabi-log/0.15.1/jcabi-log-0.15.1.jar
        at java.net.URI.create(URI.java:859)
        at com.qulice.maven.DefaultMavenEnvironment.classloader(DefaultMavenEnvironment.java:152)
        at com.qulice.checkstyle.CheckstyleValidator.validate(CheckstyleValidator.java:81)
        at com.qulice.maven.CheckMojo.run(CheckMojo.java:83)
        at com.qulice.maven.CheckMojo.doExecute(CheckMojo.java:59)
        at com.qulice.maven.AbstractQuliceMojo.execute(AbstractQuliceMojo.java:175)
        at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:132)
        ... 20 more
Caused by: java.net.URISyntaxException: Illegal character in path at index 19: file://C:/Documents and Settings/JustUser/.m2/repository/com/
jcabi/jcabi-log/0.15.1/jcabi-log-0.15.1.jar
        at java.net.URI$Parser.fail(URI.java:2829)
        at java.net.URI$Parser.checkChars(URI.java:3002)
        at java.net.URI$Parser.parseHierarchical(URI.java:3086)
        at java.net.URI$Parser.parse(URI.java:3034)
        at java.net.URI.<init>(URI.java:595)
        at java.net.URI.create(URI.java:857)
        ... 26 more
[ERROR]
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/PluginExecutionException
Z:\jcabi-ssl-maven-plugin>
</pre>

1. checkout master
2. mvn -e install -Pqulice

**Comment by dmarkov** [comment]
@yegor256 please dispatch this issue

**Comment by yegor256** [comment]
@apocarteres it's passing now on Appveyor.. I believe this problem is gone already

**Comment by apocarteres** [comment]
@yegor256 ok. thx
